#!/usr/bin/env bash

# read the puzzle input from stdin
read -r lnin

# starts on ground floor
curfl=0

# ( = +1 floor, ) = -1 floor
echo "${curfl}${lnin}" | \
    sed 's/(/+1/g' | \
    sed 's/)/-1/g' | \
    bc