#!/usr/bin/env bash

# prep the vars
declare -A lights
curline=0

# read the puzzle from stdin
while read -r puzline; do

    echo "Current line: $((++curline))"

    # Extract the command and coords
    [[ "$puzline" =~ ([^0-9]+)\ ([0-9]+),([0-9]+)[^0-9]+([0-9]+),([0-9]+) ]] && {

        # 1 = command
        # 2 = x1
        # 3 = y1
        # 4 = x2
        # 5 = y2

        # loop over each cell in the coords
        for (( x=${BASH_REMATCH[2]}; x<=${BASH_REMATCH[4]}; x++ )); do
            for (( y=${BASH_REMATCH[3]}; y<=${BASH_REMATCH[5]}; y++ )); do

                xy="${x}x$y"

                # determine what command to run
                case "${BASH_REMATCH[1]}" in
                    'turn on')
                        if [[ ! -v lights["$xy"] ]]; then
                            lights["$xy"]=1
                        fi
                        ;;
                    'turn off')
                        if [[ -v lights["$xy"] ]]; then
                            unset lights["$xy"]
                        fi
                        ;;
                    'toggle')
                        if [[ ! -v lights["$xy"] ]]; then
                            lights["$xy"]=1
                        else
                            unset lights["$xy"]
                        fi
                        ;;
                    *)
                        echo "WARNING: unknown command"
                        exit 1
                        ;;
                esac
            done
        done
    }
done

echo "Total lights on: ${#lights[@]}"