#!/usr/bin/env bash

# note: this script does not use stdin, 
#       instead it uses a filename as parameter 1

# pull in some scripts for debugigng
. ~/vardump.bash

# setup some vars
file="$1"
grandtotal=0

# get the operator line
ops="$( tail -n 1 $file )"

# separate each operator into a column with its width
echo "Getting column details.."
while true; do

    if [[ "$ops" =~ ^[[:space:]]?(.)([[:space:]]*)($|[[:space:]][^[:space:]].*) ]]; then

        char="${BASH_REMATCH[1]}"
        spaces="${BASH_REMATCH[2]}"
        remain="${BASH_REMATCH[3]}"

        col+=("$char,$((${#spaces}+1))")
    else
        echo "Something went wrong: no regex match, exiting"
        exit 1
    fi

    [[ "${#remain}" -eq 0 ]] && break
    ops="$remain"
done

# now add each line into each column
echo "Building columns.."
while IFS= read -r line; do

    for (( i=0; i<${#col[@]}; i++ )); do

        len="${col[$i]:2:1}"
        col[$i]+=",${line:0:$len}"
        line="${line:$len+1}"
    done
done < <(head -n -1 "$file")

# now that we transposed each column into a single string
# we need to process each char vertically

# process each column
echo "Processing columns.."
for column in "${col[@]}"; do

    # get the data of each column
    IFS=, read -r -a data <<< "$column"
    char="${data[0]}"
    len="${data[1]}"
    unset temp

    # loop over each number and store in temp var
    for (( x=0; x<$len; x++ )); do

        [[ -n $temp ]] && temp+="$char"

        for (( y=2; y<${#data[@]}; y++ )); do

            cell="${data[$y]:x:1}"
            [[ $cell =~ ^[0-9]$ ]] && temp+="$cell"
        done
    done

    # calcluate the final string
    (( grandtotal+=$( echo "$temp" | bc ) ))
done

echo "Grand total: $grandtotal"