#!/usr/bin/env bash

# setup some vars
numnice=0

# read the puzzle input from stdin
while read -r puzline; do

    # check for pairs of letters
    for letter1 in {a..z}; do
        for letter2 in {a..z}; do
            if [[ "$puzline" =~ $letter1$letter2.*$letter1$letter2 ]]; then
                
                # check repeating letter with an inbetweener
                for letter3 in {a..z}; do
                    if [[ "$puzline" =~ $letter3.$letter3 ]]; then
                        ((numnice++))
                        break 3
                    fi
                done
            fi
        done
    done

done

echo "Number of nice puzzles: $numnice"